const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");const $=id=>document.getElementById(id);
const heroes={knight:{name:"Knight",hp:120,damage:18,speed:4},rogue:{name:"Rogue",hp:85,damage:25,speed:6},mage:{name:"Mage",hp:75,damage:34,speed:4}};
const defaults={coins:0,stage:1,xp:0,hero:"knight",upgrades:{damage:0,hp:0,speed:0}};let save=load(),player,foes=[],running=false,won=false,last=0,keys={left:false,right:false},attackCooldown=0,spawnTimer=0,boss=false;
function load(){try{const v=JSON.parse(localStorage.getItem("neonQuestSave"));return v&&v.coins>=0?{...defaults,...v,upgrades:{...defaults.upgrades,...v.upgrades}}:structuredClone(defaults)}catch(e){return structuredClone(defaults)}}
function persist(){localStorage.setItem("neonQuestSave",JSON.stringify(save));render()}
function stats(){const h=heroes[save.hero];return{hp:h.hp+save.upgrades.hp*20,damage:h.damage+save.upgrades.damage*5,speed:h.speed+save.upgrades.speed*.5}}
function render(){$("coins").textContent=save.coins;$("stage").textContent=save.stage;$("xp").textContent=save.xp;renderShop();renderHeroes()}
function renderShop(){const items=[["damage","Damage +5",60],["hp","Max HP +20",70],["speed","Speed +0.5",80]];$("shopItems").innerHTML=items.map(([k,n,c])=>`<div class="card"><h3>${n}</h3><p>Level ${save.upgrades[k]} • Cost ${c} coins</p><button data-buy="${k}">BUY</button></div>`).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
function renderHeroes(){const keysH=Object.keys(heroes);$("heroItems").innerHTML=keysH.map(k=>{const h=heroes[k],selected=save.hero===k;return`<div class="card"><h3>${h.name} ${selected?"✓":""}</h3><p>HP ${h.hp} • Damage ${h.damage} • Speed ${h.speed}</p><button data-hero="${k}" ${selected?"disabled":""}>SELECT</button></div>`}).join("");document.querySelectorAll("[data-hero]").forEach(b=>b.onclick=()=>{save.hero=b.dataset.hero;persist();$("status").textContent=heroes[save.hero].name+" selected."})}
function buy(k){const cost={damage:60,hp:70,speed:80}[k];if(save.coins<cost){$("status").textContent="Not enough coins.";return}save.coins-=cost;save.upgrades[k]++;persist();$("status").textContent="Upgrade purchased!"}
function startStage(){if(running)return;const s=stats();player={x:80,y:300,w:38,h:58,hp:s.hp,maxHp:s.hp,damage:s.damage,speed:s.speed};foes=[];running=true;won=false;boss=save.stage===5;spawnTimer=0;attackCooldown=0;last=performance.now();$("next").disabled=true;$("start").disabled=true;$("status").textContent=boss?"BOSS STAGE! Defeat the Guardian!":"Stage "+save.stage+" — defeat the enemies!";requestAnimationFrame(loop)}
function spawnEnemy(){const isBoss=boss&&foes.length===0&&save.xp%2===0;const hp=isBoss?180+save.stage*35:30+save.stage*12;foes.push({x:canvas.width-70,y:isBoss?250:300-Math.random()*120,w:isBoss?72:34,h:isBoss?90:45,hp,maxHp:hp,damage:isBoss?12:5+save.stage,speed:isBoss?0.7:1.2+save.stage*.12,isBoss})}
function attack(){if(!running||attackCooldown>0)return;attackCooldown=.35;const range=110;let target=foes.find(f=>f.x>player.x&&f.x-player.x<range);if(target){target.hp-=player.damage;if(target.hp<=0){save.coins+=target.isBoss?250:15+save.stage*3;save.xp+=target.isBoss?100:10;foes=foes.filter(f=>f!==target);if(target.isBoss)finishStage(true)}}}
function finishStage(success){running=false;won=success;if(success){if(save.stage<5)save.stage++;$("status").textContent=save.stage===1?"Stage complete!":"Stage complete! You earned coins.";persist();$("next").disabled=save.stage>5;$("start").disabled=false}}
function update(dt){if(keys.left)player.x-=player.speed*60*dt;if(keys.right)player.x+=player.speed*60*dt;player.x=Math.max(20,Math.min(canvas.width-player.w-20,player.x));attackCooldown=Math.max(0,attackCooldown-dt);spawnTimer-=dt;if(!boss&&spawnTimer<=0){spawnEnemy();spawnTimer=Math.max(.8,2-save.stage*.15)}if(boss&&foes.length===0)spawnEnemy();for(const f of foes){if(f.x>player.x+player.w)f.x-=f.speed*60*dt;else{player.hp-=f.damage*dt;if(player.hp<=0){running=false;$("status").textContent="Defeated! Try the stage again.";$("start").disabled=false}}}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#11182b";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#17203a";for(let i=0;i<canvas.width;i+=48)ctx.fillRect(i,350,24,70);ctx.fillStyle="#55d6ff";ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle="#ff4f76";for(const f of foes)ctx.fillRect(f.x,f.y,f.w,f.h);ctx.fillStyle="#fff";ctx.font="bold 18px system-ui";ctx.fillText("HP "+Math.max(0,Math.ceil(player.hp))+"/"+player.maxHp,18,28);for(const f of foes){ctx.fillStyle="#e8e8ef";ctx.fillRect(f.x,f.y-12,f.w,5);ctx.fillStyle="#61e294";ctx.fillRect(f.x,f.y-12,f.w*Math.max(0,f.hp/f.maxHp),5);if(f.isBoss){ctx.fillStyle="#ffcf4a";ctx.font="bold 16px system-ui";ctx.fillText("GUARDIAN",f.x-5,f.y-22)}}}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.screen).classList.add("active")});
$("start").onclick=startStage;$("next").onclick=startStage;$("attack").onclick=attack;$("left").onpointerdown=()=>keys.left=true;$("left").onpointerup=()=>keys.left=false;$("left").onpointerleave=()=>keys.left=false;$("right").onpointerdown=()=>keys.right=true;$("right").onpointerup=()=>keys.right=false;$("right").onpointerleave=()=>keys.right=false;
addEventListener("keydown",e=>{if(e.key==="ArrowLeft")keys.left=true;if(e.key==="ArrowRight")keys.right=true;if(e.key===" "||e.key==="Enter"){e.preventDefault();attack()}});addEventListener("keyup",e=>{if(e.key==="ArrowLeft")keys.left=false;if(e.key==="ArrowRight")keys.right=false});
$("reset").onclick=()=>{if(confirm("Reset all progress?")){localStorage.removeItem("neonQuestSave");save=load();render();$("status").textContent="Save reset."}};
render();