package com.aether.echoes

data class Quest(val id:String,val title:String,val description:String,val goal:Int,val rewardGold:Int,var progress:Int=0,var done:Boolean=false)
data class Equipment(val id:String,val name:String,val attack:Int,val defense:Int,val rarity:Rarity)
data class DialogueLine(val speaker:String,val text:String)
class QuestSystem{val quests=linkedMapOf("awakening" to Quest("awakening","The First Echo","Defeat 3 Aether creatures.",3,40),"ruins" to Quest("ruins","Whispers of the Ruins","Reach the Forgotten Ruins.",1,75),"tower" to Quest("tower","Climb the Tower","Defeat the Aether Tower guardian.",1,150));fun enemyDefeated(){quests.values.firstOrNull{!it.done&&it.id=="awakening"}?.let{it.progress++;if(it.progress>=it.goal)it.done=true}}}
class DialogueSystem{val archivist=listOf(DialogueLine("Archivist Mira","The Aether remembers every life that touches it."),DialogueLine("Archivist Mira","If the Heart awakens, the world may awaken with it."),DialogueLine("Kael","Then I will reach the Heart before the Void does."))}
class EquipmentSystem{val items=listOf(Equipment("aether_blade","Aether Blade",4,0,Rarity.UNCOMMON),Equipment("ruin_guard","Ruin Guard",0,4,Rarity.RARE),Equipment("heart_ring","Heart Ring",8,8,Rarity.LEGENDARY));var equipped:Equipment?=null;fun attackBonus()=equipped?.attack?:0;fun defenseBonus()=equipped?.defense?:0}
class Boss(val id:Int,val chapter:World.Chapter,sx:Float):Body(sx,11f*T-76f,76f,76f){var hp=220+chapter.id*80;val maxHp=hp;var phase=1;var timer=0f;var flash=0f;var dead=false;var deadT=0f;var dir=-1;fun update(g:Game,dt:Float){if(dead){deadT-=dt;return};timer-=dt;flash-=dt;val dx=g.player.x-x;dir=if(dx>=0)1 else -1;vx=if(kotlin.math.abs(dx)>90f)dir*(75f+chapter.id*8f)else 0f;if(timer<=0f){timer=if(phase==1)1.15f else .72f;if(kotlin.math.abs(dx)<150f)g.player.hurt(g,18+chapter.id*2,x)else g.fireBlast(x+w/2,y+h/2,dir)};if(hp<maxHp*.55f)phase=2;if(hp<=0){dead=true;deadT=.8f;vx=0f};vy=kotlin.math.min(vy+1800f*dt,800f);move(g.world,dt)};fun hurt(d:Int,dir:Int){if(dead)return;hp-=d;flash=.12f;vx=dir*120f;vy=-120f}}
