package com.aether.echoes
import android.content.Context
import android.graphics.Canvas
import android.graphics.LinearGradient
import android.graphics.Paint
import android.graphics.Shader
import kotlin.math.abs
import kotlin.math.floor
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin
import kotlin.random.Random
import java.util.concurrent.Executors

class Pickup(val id:Int,val x:Float,val y:Float,val type:String){var taken=false}
class Particles(private val n:Int){private val x=FloatArray(n);private val y=FloatArray(n);private val vx=FloatArray(n);private val vy=FloatArray(n);private val life=FloatArray(n);private val col=IntArray(n);private var next=0
 fun burst(px:Float,py:Float,count:Int,color:Int){repeat(count){val i=next;next=(next+1)%n;x[i]=px;y[i]=py;vx[i]=Random.nextFloat()*400-200;vy[i]=Random.nextFloat()*-300;life[i]=.4f;col[i]=color}}
 fun update(dt:Float){for(i in 0 until n)if(life[i]>0){life[i]-=dt;vy[i]+=900*dt;x[i]+=vx[i]*dt;y[i]+=vy[i]*dt}}
 fun draw(c:Canvas,p:Paint){for(i in 0 until n)if(life[i]>0){p.color=col[i];p.alpha=(life[i]*600).toInt().coerceIn(0,255);c.drawCircle(x[i],y[i],3f,p)}}}

class Game(ctx:Context){
 val controls=Controls();val world=World();val player=Player();val particles=Particles(160);val audio=AudioManager(ctx);val inv=Inventory();val abilities=HashSet<String>();val flags=HashSet<String>();private val saves=SaveManager(ctx.filesDir);private val io=Executors.newSingleThreadExecutor();private val enemies=ArrayList<Enemy>();private val pickups=ArrayList<Pickup>();var gold=0;var level=1;var xp=0;var cp=0;@Volatile var paused=false;var hitStop=0f;var shake=0f;var shakeOn=true;private var pendingHp=0;private var pendingAether=0;private var camX=0f;private var camY=0f;private var oldCamX=0f;private var oldCamY=0f;private var respawnT=0f;private var animT=0f;private var combatT=0f;private var toast="";private var toastT=0f;private var sw=0;private var sh=0;private var scale=1f;private var viewW=800f;private val p=Paint(Paint.ANTI_ALIAS_FLAG);private val sky=Paint();private val projX=FloatArray(8);private val projY=FloatArray(8);private val projV=FloatArray(8);private val projL=FloatArray(8)
 init{pickups.add(Pickup(0,8*T,12*T-30,"double_jump"));pickups.add(Pickup(1,22*T,12*T-30,"wall_jump"));pickups.add(Pickup(2,29*T,12*T-30,"dash"));pickups.add(Pickup(3,43*T,3*T-30,"chest"));saves.load()?.let{applySave(it)};for(k in pickups)k.taken=flags.contains("p"+k.id);respawn()}
 fun maxHp()=100+(level-1)*10;fun armor()=1+level/2;fun addShake(v:Float){if(shakeOn)shake=max(shake,v)}
 private fun applySave(d:SaveData){pendingHp=d.hp;pendingAether=d.aether;cp=d.cp;gold=d.gold;level=d.level;xp=d.xp;shakeOn=d.shake;abilities.addAll(d.abilities);flags.addAll(d.flags);inv.load(d.inventory);controls.scale=d.ctrlScale;controls.opacity=d.ctrlOpacity}
 private fun spawn(){enemies.clear();world.enemySpawnCols.forEachIndexed{i,c->if(!flags.contains("k"+i))enemies.add(Enemy(i,c*T,12*T))};player.reset(world.checkpoints[cp].first,world.checkpoints[cp].second,this);if(pendingHp>0){player.hp=pendingHp.coerceIn(1,maxHp());player.aether=pendingAether.coerceIn(0,100).toFloat();pendingHp=0};controls.clearPressed();oldCamX=camX;oldCamY=camY}
 private fun toast(s:String){toast=s;toastT=2f}
 fun usePotion(){if(inv.remove("potion",1)){player.hp=min(maxHp(),player.hp+40);audio.sfx("potion")}}
 fun shutdown(){io.shutdownNow();audio.release()}
 fun toSave()=SaveData(2,cp,player.hp,player.aether.toInt(),gold,level,xp,abilities.toSet(),inv.snapshot(),flags.toSet(),controls.scale,controls.opacity,shakeOn)
 fun saveNow(sync:Boolean=false){val d=toSave();if(sync||io.isShutdown)saves.save(d)else io.execute{saves.save(d)}}
 fun playerStrike(pl:Player){val bx=if(pl.facing>0)pl.x+pl.w else pl.x-52f;for(e in enemies)if(e.state!=EState.DEAD&&e.lastSwing!=pl.swingId&&overlap(bx,pl.y,52f,44f,e.x,e.y,e.w,e.h)){e.lastSwing=pl.swingId;val crit=Random.nextFloat()<.1f;val dmg=(8+level*2)*(if(pl.combo==2)1.5f else 1f)*(if(crit)2f else 1f);audio.sfx(if(crit)"crit"else"hit");e.hurt(this,max(1,dmg.toInt()-e.armor),pl.facing);particles.burst(e.x+e.w/2,e.y+e.h/2,8,0xFFFFE2A0.toInt());addShake(5f)}}
 fun fireBlast(x:Float,y:Float,dir:Int){for(i in projL.indices)if(projL[i]<=0){projX[i]=x;projY[i]=y;projV[i]=dir*520f;projL[i]=1.2f;return}}
 fun update(dt:Float){audio.update(dt);if(paused)return;animT+=dt;if(toastT>0)toastT-=dt;shake=max(0f,shake-40*dt);if(hitStop>0){hitStop-=dt;return};oldCamX=camX;oldCamY=camY;if(!player.dead)player.update(this,dt);else{if(respawnT<=0)respawnT=1f;respawnT-=dt;if(respawnT<=0){respawnT=0f;spawn()}}
 val it=enemies.iterator();while(it.hasNext()){val e=it.next();e.update(this,dt);if(e.state==EState.DEAD&&e.deadT<=0){flags.add("k"+e.id);gold+=5;xp+=10;inv.add("aether_shard",1);audio.sfx("enemy_death");it.remove();while(xp>=level*30&&level<99){xp-=level*30;level++;player.hp=maxHp();audio.sfx("levelup")}}}
 for(i in projL.indices)if(projL[i]>0){projL[i]-=dt;projX[i]+=projV[i]*dt;if(world.solid(floor(projX[i]/T).toInt(),floor(projY[i]/T).toInt()))projL[i]=0f;for(e in enemies)if(e.state!=EState.DEAD&&overlap(projX[i]-8,projY[i]-8,16f,16f,e.x,e.y,e.w,e.h)){e.hurt(this,(8+level*2)*2,if(projV[i]>0)1 else -1);projL[i]=0f;break}}
 if(!player.dead)for(k in pickups)if(!k.taken&&overlap(player.x,player.y,player.w,player.h,k.x-16,k.y-16,32f,32f)){k.taken=true;flags.add("p"+k.id);audio.sfx(if(k.type=="chest")"chest"else"pickup");if(k.type=="chest"){gold+=100;inv.add("potion",3);toast("Chest: +100 gold, +3 tonics")}else{abilities.add(k.type);toast("Learned: "+k.type)};particles.burst(k.x,k.y,14,0xFF9FE8FF.toInt())}
 var fight=false;for(e in enemies)if(e.state==EState.CHASE||e.state==EState.ATTACK)fight=true;if(fight)combatT=2f else combatT-=dt;audio.music(if(combatT>0)"combat"else"explore");particles.update(dt);val tx=(player.x+player.w/2-viewW/2+player.facing*60).coerceIn(0f,max(0f,world.cols*T-viewW));camX+=(tx-camX)*min(1f,8f*dt);camY+=((player.y+player.h/2-300).coerceIn(0f,72f)-camY)*min(1f,8f*dt)}
 private fun resize(w:Int,h:Int){sw=w;sh=h;scale=h/600f;viewW=w/scale;controls.layout(w,h);sky.shader=LinearGradient(0f,0f,0f,h.toFloat(),0xFF1B2447.toInt(),0xFF6A5A8E.toInt(),Shader.TileMode.CLAMP)}
 fun draw(c:Canvas,w:Int,h:Int,alpha:Float=1f){if(w!=sw||h!=sh)resize(w,h);c.drawRect(0f,0f,w.toFloat(),h.toFloat(),sky);val cx=oldCamX+(camX-oldCamX)*alpha;val cy=oldCamY+(camY-oldCamY)*alpha;c.save();c.scale(scale,scale);c.translate(-cx,-cy);val a=floor(cx/T).toInt();for(y in 0 until world.rows)for(x in a..a+(viewW/T).toInt()+2)if(x in 0 until world.cols&&world.solid(x,y)){p.color=0xFF2E2A45.toInt();c.drawRect(x*T,y*T,x*T+T,y*T+T,p);if(!world.solid(x,y-1)){p.color=0xFF5D8B61.toInt();c.drawRect(x*T,y*T,x*T+T,y*T+7,p)}};for(k in pickups)if(!k.taken){p.color=if(k.type=="chest")0xFFE0B040.toInt()else 0xFF9FE8FF.toInt();c.drawCircle(k.x,k.y+sin(animT*3)*4,if(k.type=="chest")14f else 11f,p)};for(e in enemies){val ex=e.px+(e.x-e.px)*alpha;val ey=e.py+(e.y-e.py)*alpha;Sprites.drawWolf(c,p,ex,ey,e.w,e.h,e.dir,animT+e.id,e.flash>0,e.state==EState.ATTACK&&e.timer>.05,abs(e.vx)>10)};for(i in projL.indices)if(projL[i]>0){p.color=0xFF7FE0FF.toInt();c.drawCircle(projX[i],projY[i],9f,p)};val px=player.px+(player.x-player.px)*alpha;val py=player.py+(player.y-player.py)*alpha;if(!player.dead)Sprites.drawKael(c,p,px,py,player.w,player.h,player.facing,animT,player.vx,player.vy,player.onGround,player.atkT>0,player.combo,player.dashT>0);particles.draw(c,p);c.restore();val u=h/600f;p.color=0x88000000.toInt();c.drawRect(20*u,20*u,280*u,58*u,p);p.color=0xFFC04848.toInt();c.drawRect(24*u,24*u,(24+252f*player.hp/maxHp())*u,38*u,p);p.color=0xFF4890D8.toInt();c.drawRect(24*u,42*u,(24+252f*player.aether/player.maxAether)*u,52*u,p);p.color=0xFFFFFFFF.toInt();p.textSize=18*u;p.textAlign=Paint.Align.LEFT;c.drawText("Lv "+level+"   Gold "+gold+"   Tonics "+inv.count("potion"),24*u,78*u,p);if(toastT>0){p.textAlign=Paint.Align.CENTER;c.drawText(toast,w/2f,60*u,p)};controls.draw(c);if(paused){p.color=0xAA000000.toInt();c.drawRect(0f,0f,w.toFloat(),h.toFloat(),p);p.color=0xFFFFFFFF.toInt();p.textAlign=Paint.Align.CENTER;p.textSize=40*u;c.drawText("PAUSED - tap to resume",w/2f,h/2f,p)}}
}