package com.aether.echoes
import android.content.Context
import android.graphics.*
import kotlin.math.*
import kotlin.random.Random
import java.util.concurrent.Executors
class ParticlePool(private val max:Int=180){private val x=FloatArray(max);private val y=FloatArray(max);private val vx=FloatArray(max);private val vy=FloatArray(max);private val life=FloatArray(max);private var n=0;fun burst(px:Float,py:Float,count:Int){repeat(count){val i=n%max;n++;x[i]=px;y[i]=py;vx[i]=Random.nextFloat()*360f-180f;vy[i]=Random.nextFloat()*300f-300f;life[i]=.35f}};fun update(dt:Float){for(i in 0 until max)if(life[i]>0){life[i]-=dt;vy[i]+=700*dt;x[i]+=vx[i]*dt;y[i]+=vy[i]*dt}};fun draw(c:Canvas,p:Paint){for(i in 0 until max)if(life[i]>0){p.color=0xFF9FE8FF.toInt();p.alpha=(life[i]*700).toInt().coerceIn(0,255);c.drawCircle(x[i],y[i],3f,p)}}}
class Game(ctx:Context){
 val controls=Controls();val world=World();val player=Player();val particles=ParticlePool();val inv=Inventory();val abilities=HashSet<String>();val flags=HashSet<String>();val quests=QuestSystem();val dialogue=DialogueSystem();val equipment=EquipmentSystem();val audio=AudioManager(ctx)
 private val save=SaveManager(ctx.filesDir);private val io=Executors.newSingleThreadExecutor();private val enemies=ArrayList<Enemy>();private val bosses=ArrayList<Boss>()
 private val projX=FloatArray(10);private val projY=FloatArray(10);private val projV=FloatArray(10);private val projL=FloatArray(10)
 var gold=0;var level=1;var xp=0;var cp=0;var chapter=1;var paused=false;var hitStop=0f;var shake=0f;var shakeOn=true
 var showInventory=false;var showQuest=false;var showSettings=false
 private var respawnTimer=0f;private var camX=0f;private var camY=0f;private var oldX=0f;private var oldY=0f;private var sw=0;private var sh=0;private var scale=1f;private var viewW=800f;private var toast="";private var toastT=0f
 private val p=Paint(Paint.ANTI_ALIAS_FLAG);private val sky=Paint()
 init{save.load()?.let{d->cp=d.cp;gold=d.gold;level=d.level;xp=d.xp;shakeOn=d.shake;abilities.addAll(d.abilities);flags.addAll(d.flags);inv.load(d.inventory);controls.scale=d.ctrlScale;controls.opacity=d.ctrlOpacity};spawn()}
 fun maxHp()=100+(level-1)*10
 fun armor()=1+level/2
 fun addShake(v:Float){if(shakeOn)shake=max(shake,v)}
 private fun toast(s:String){toast=s;toastT=2.2f}
 private fun spawn(){val s=world.checkpoints[cp.coerceIn(0,world.checkpoints.lastIndex)];player.reset(s.first,s.second,this);enemies.clear();bosses.clear();world.enemySpawnCols.forEachIndexed{i,col->if(!flags.contains("k"+i))enemies.add(Enemy(i,col*T,12f*T))};world.chapters.forEach{ch->if(!flags.contains("b"+ch.id))bosses.add(Boss(ch.id,ch,ch.bossCol*T))};controls.clearPressed();oldX=camX;oldY=camY}
 fun usePotion(){if(inv.remove("potion",1)){player.hp=min(maxHp(),player.hp+40);audio.sfx("potion")}}
 fun saveNow(sync:Boolean=false){val d=SaveData(2,cp,player.hp,player.aether.toInt(),gold,level,xp,abilities.toSet(),inv.snapshot(),flags.toSet(),controls.scale,controls.opacity,shakeOn);if(sync)save.save(d)else io.execute{save.save(d)}}
 fun shutdown(){io.shutdownNow();audio.release()}
 fun playerStrike(pl:Player){val bx=if(pl.facing>0)pl.x+pl.w else pl.x-52f;for(e in enemies)if(e.state!=EState.DEAD&&e.lastSwing!=pl.swingId&&overlap(bx,pl.y,52f,44f,e.x,e.y,e.w,e.h)){e.lastSwing=pl.swingId;val d=((10+level*2+equipment.attackBonus())*(if(pl.combo==2)1.5f else 1f)).toInt();e.hurt(this,d,pl.facing);audio.sfx("hit");particles.burst(e.x+e.w/2,e.y+e.h/2,8);addShake(4f)};for(b in bosses)if(!b.dead&&overlap(bx,pl.y,52f,44f,b.x,b.y,b.w,b.h)){val d=((10+level*2+equipment.attackBonus())*(if(pl.combo==2)1.5f else 1f)).toInt();b.hurt(d,pl.facing);audio.sfx("hit");particles.burst(b.x+b.w/2,b.y+b.h/2,10);addShake(7f)}}
 fun fireBlast(x:Float,y:Float,dir:Int){for(i in projL.indices)if(projL[i]<=0){projX[i]=x;projY[i]=y;projV[i]=dir*520f;projL[i]=1.2f;return}}
 private fun enemyDeath(e:Enemy){flags.add("k"+e.id);gold+=5;xp+=10;quests.enemyDefeated();inv.add("aether_shard",1);audio.sfx("enemy_death");if(xp>=level*30&&level<99){xp-=level*30;level++;player.hp=maxHp();audio.sfx("levelup");toast("Level "+level+"!")}}
 fun update(dt:Float){if(paused)return;toastT=max(0f,toastT-dt);shake=max(0f,shake-40f*dt);oldX=camX;oldY=camY;if(hitStop>0){hitStop-=dt;return};if(!player.dead)player.update(this,dt)else{if(respawnTimer<=0)respawnTimer=1f;respawnTimer-=dt;if(respawnTimer<=0){respawnTimer=0f;spawn()}}
  val it=enemies.iterator();while(it.hasNext()){val e=it.next();e.update(this,dt);if(e.state==EState.DEAD&&e.deadT<=0){enemyDeath(e);it.remove()}}
  val bi=bosses.iterator();while(bi.hasNext()){val b=bi.next();b.update(this,dt);if(b.dead&&b.deadT<=0){flags.add("b"+b.chapter.id);gold+=100+b.chapter.id*50;xp+=100;chapter=min(7,b.chapter.id+1);toast(if(chapter<=7)"Chapter "+chapter+": "+world.chapters[chapter-1].name else "The Heart is silent.");audio.sfx("enemy_death");saveNow();bi.remove()}}
  for(i in projL.indices)if(projL[i]>0){projL[i]-=dt;projX[i]+=projV[i]*dt;for(e in enemies)if(e.state!=EState.DEAD&&overlap(projX[i]-8,projY[i]-8,16f,16f,e.x,e.y,e.w,e.h)){e.hurt(this,20,if(projV[i]>0)1 else -1);projL[i]=0f;break};if(projL[i]>0)for(b in bosses)if(!b.dead&&overlap(projX[i]-8,projY[i]-8,16f,16f,b.x,b.y,b.w,b.h)){b.hurt(20,if(projV[i]>0)1 else -1);projL[i]=0f;break}}
  particles.update(dt);chapter=world.chapterIndexAt(player.x);for(i in world.checkpoints.indices){val q=world.checkpoints[i];if(i!=cp&&abs(player.x+player.w/2-q.first)<40&&abs(player.y+player.h-q.second)<20){cp=i;player.hp=maxHp();audio.sfx("checkpoint");toast("Checkpoint");saveNow()}}
  val target=(player.x+player.w/2-viewW/2+player.facing*60).coerceIn(0f,max(0f,world.cols*T-viewW));camX+=(target-camX)*min(1f,8f*dt);camY+=((player.y+player.h/2-300).coerceIn(0f,72f)-camY)*min(1f,8f*dt);audio.music(if(bosses.any{!it.dead&&abs(it.x-player.x)<320})"combat" else "explore")}
 private fun resize(w:Int,h:Int){sw=w;sh=h;scale=h/600f;viewW=w/scale;controls.layout(w,h);sky.shader=LinearGradient(0f,0f,0f,h.toFloat(),0xFF151C3D.toInt(),0xFF6A5A8E.toInt(),Shader.TileMode.CLAMP)}
 fun draw(c:Canvas,w:Int,h:Int,a:Float=1f){if(w!=sw||h!=sh)resize(w,h);c.drawRect(0f,0f,w.toFloat(),h.toFloat(),sky);val cx=oldX+(camX-oldX)*a;val cy=oldY+(camY-oldY)*a;c.save();c.scale(scale,scale);c.translate(-cx,-cy)
  val x0=floor(cx/T).toInt();for(y in 0 until world.rows)for(x in x0..x0+(viewW/T).toInt()+2)if(x in 0 until world.cols&&world.solid(x,y)){p.color=0xFF2E2A45.toInt();c.drawRect(x*T,y*T,x*T+T,y*T+T,p);if(!world.solid(x,y-1)){p.color=0xFF5D8B61.toInt();c.drawRect(x*T,y*T,x*T+T,y*T+7,p)}}
  for(b in bosses)if(!b.dead){p.color=if(b.flash>0)Color.WHITE else 0xFF7A3F9E.toInt();c.drawRoundRect(b.x,b.y,b.x+b.w,b.y+b.h,18f,18f,p);p.color=Color.WHITE;c.drawCircle(b.x+b.w*.3f,b.y+b.h*.35f,7f,p);c.drawCircle(b.x+b.w*.7f,b.y+b.h*.35f,7f,p);p.color=0xAA000000.toInt();c.drawRect(b.x,b.y-18,b.x+b.w,b.y-10,p);p.color=0xFFE85B78.toInt();c.drawRect(b.x,b.y-18,b.x+b.w*(b.hp.toFloat()/b.maxHp),b.y-10,p)}
  for(e in enemies){p.color=if(e.flash>0)Color.WHITE else 0xFF6D5B86.toInt();c.drawOval(e.x,e.y,e.x+e.w,e.y+e.h,p);p.color=0xFFFF4F60.toInt();c.drawCircle(e.x+e.w*.7f,e.y+12,2.5f,p)}
  for(i in projL.indices)if(projL[i]>0){p.color=0xFF8FE8FF.toInt();c.drawCircle(projX[i],projY[i],8f,p)}
  if(!player.dead){p.color=0xFF2F4A7A.toInt();c.drawRect(player.x,player.y,player.x+player.w,player.y+player.h,p);p.color=0xFFE8C8A8.toInt();c.drawCircle(player.x+player.w/2,player.y+10,8f,p);if(player.atkT>0){p.color=0xFFBFF0FF.toInt();p.style=Paint.Style.STROKE;p.strokeWidth=5f;c.drawArc(player.x-24,player.y-20,player.x+player.w+24,player.y+player.h+20,if(player.facing>0)-60f else 120f,120f,false,p);p.style=Paint.Style.FILL}}
  particles.draw(c,p);c.restore();val u=h/600f;p.alpha=255;p.color=0x88000000.toInt();c.drawRect(20*u,20*u,300*u,58*u,p);p.color=0xFFC04848.toInt();c.drawRect(24*u,24*u,(24+252f*player.hp/maxHp())*u,38*u,p);p.color=0xFF4890D8.toInt();c.drawRect(24*u,42*u,(24+252f*player.aether/player.maxAether)*u,52*u,p);p.color=Color.WHITE;p.textSize=18*u;p.textAlign=Paint.Align.LEFT;c.drawText("Lv "+level+"   Gold "+gold+"   Tonics "+inv.count("potion"),24*u,78*u,p);p.textAlign=Paint.Align.RIGHT;c.drawText("CHAPTER "+chapter+"  "+world.chapters[chapter-1].name,w-20*u,34*u,p);if(toastT>0){p.textAlign=Paint.Align.CENTER;c.drawText(toast,w/2f,90*u,p)}
  if(showInventory||showQuest||showSettings){p.color=0xEE10172B.toInt();c.drawRoundRect(40*u,90*u,w-40*u,h-90*u,18*u,18*u,p);p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=28*u;c.drawText(if(showInventory)"INVENTORY" else if(showQuest)"QUESTS" else "SETTINGS",w/2f,130*u,p);p.textAlign=Paint.Align.LEFT;p.textSize=18*u;if(showInventory){c.drawText("Tonics: "+inv.count("potion"),70*u,175*u,p);c.drawText("Aether Shards: "+inv.count("aether_shard"),70*u,205*u,p);c.drawText("Equipment: "+(equipment.equipped?.name?:"None"),70*u,235*u,p)}else if(showQuest){var yy=175f;for(q in quests.quests.values){c.drawText((if(q.done)"✓" else "•")+" "+q.title+": "+q.progress+"/"+q.goal,70*u,yy*u,p);yy+=34f}}else{c.drawText("Shake: "+(if(shakeOn)"ON" else "OFF"),70*u,175*u,p);c.drawText("Tap to close",70*u,210*u,p)}}
  controls.draw(c);if(paused){p.color=0xAA000000.toInt();c.drawRect(0f,0f,w.toFloat(),h.toFloat(),p);p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=40*u;c.drawText("PAUSED",w/2f,h/2f,p)}}
}