package com.aether.echoes
import android.content.Context
import android.graphics.Canvas
import android.graphics.LinearGradient
import android.graphics.Paint
import android.graphics.Shader
import kotlin.math.*
import java.util.concurrent.Executors
class Particle(var x:Float,var y:Float,var vx:Float,var vy:Float,var life:Float)
class ParticlePool(private val n:Int=120){private val a=ArrayList<Particle>();fun burst(x:Float,y:Float,count:Int){repeat(count.coerceAtMost(n-a.size)){a.add(Particle(x,y,(-180..180).random().toFloat(),(-260..-60).random().toFloat(),.35f))}};fun update(dt:Float){val it=a.iterator();while(it.hasNext()){val q=it.next();q.life-=dt;q.vy+=700*dt;q.x+=q.vx*dt;q.y+=q.vy*dt;if(q.life<=0)it.remove()}};fun draw(c:Canvas,p:Paint){for(q in a){p.color=0xFF9FE8FF.toInt();p.alpha=(q.life*700).toInt().coerceIn(0,255);c.drawCircle(q.x,q.y,3f,p)}}}
class Game(ctx:Context){
 val controls=Controls();val world=World();val player=Player();val particles=ParticlePool();val inv=Inventory();val abilities=HashSet<String>();val flags=HashSet<String>();private val save=SaveManager(ctx.filesDir);private val io=Executors.newSingleThreadExecutor();private val enemies=ArrayList<Enemy>();private val projX=FloatArray(8);private val projY=FloatArray(8);private val projV=FloatArray(8);private val projL=FloatArray(8);var gold=0;var level=1;var xp=0;var cp=0;var paused=false;var hitStop=0f;var shake=0f;var shakeOn=true;private var respawn=0f;private var anim=0f;private var camX=0f;private var camY=0f;private var oldX=0f;private var oldY=0f;private var sw=0;private var sh=0;private var scale=1f;private var viewW=800f;private val p=Paint(3);private val sky=Paint()
 init{save.load()?.let{d->cp=d.cp;gold=d.gold;level=d.level;xp=d.xp;shakeOn=d.shake;abilities.addAll(d.abilities);flags.addAll(d.flags);inv.load(d.inventory);controls.scale=d.ctrlScale;controls.opacity=d.ctrlOpacity};spawn()}
 fun maxHp()=100+(level-1)*10;fun armor()=1+level/2;fun addShake(v:Float){if(shakeOn)shake=max(shake,v)}
 private fun spawn(){val s=world.checkpoints[cp.coerceIn(0,world.checkpoints.lastIndex)];player.reset(s.first,s.second,this);enemies.clear();world.enemySpawnCols.forEachIndexed{i,c->if(!flags.contains("k"+i))enemies.add(Enemy(i,c*T,12*T))};controls.clearPressed();oldX=camX;oldY=camY}
 fun usePotion(){if(inv.remove("potion",1))player.hp=min(maxHp(),player.hp+40)}
 fun saveNow(sync:Boolean=false){val d=SaveData(2,cp,player.hp,player.aether.toInt(),gold,level,xp,abilities.toSet(),inv.snapshot(),flags.toSet(),controls.scale,controls.opacity,shakeOn);if(sync)save.save(d)else io.execute{save.save(d)}}
 fun shutdown(){io.shutdownNow()}
 fun playerStrike(pl:Player){val bx=if(pl.facing>0)pl.x+pl.w else pl.x-52f;for(e in enemies)if(e.state!=EState.DEAD&&e.lastSwing!=pl.swingId&&overlap(bx,pl.y,52f,44f,e.x,e.y,e.w,e.h)){e.lastSwing=pl.swingId;e.hurt(this,(10+level*2)*(if(pl.combo==2)1.5f else 1f).toInt(),pl.facing);particles.burst(e.x+e.w/2f,e.y+e.h/2f,8);addShake(5f)}}
 fun fireBlast(x:Float,y:Float,dir:Int){for(i in projL.indices)if(projL[i]<=0){projX[i]=x;projY[i]=y;projV[i]=dir*520f;projL[i]=1.2f;return}}
 fun update(dt:Float){if(paused)return;anim+=dt;shake=max(0f,shake-40*dt);oldX=camX;oldY=camY;if(hitStop>0){hitStop-=dt;return};if(!player.dead)player.update(this,dt)else{if(respawn<=0)respawn=1;respawn-=dt;if(respawn<=0){respawn=0;spawn()}};val it=enemies.iterator();while(it.hasNext()){val e=it.next();e.update(this,dt);if(e.state==EState.DEAD&&e.deadT<=0){flags.add("k"+e.id);gold+=5;xp+=10;inv.add("aether_shard",1);it.remove()}};for(i in projL.indices)if(projL[i]>0){projL[i]-=dt;projX[i]+=projV[i]*dt;for(e in enemies)if(e.state!=EState.DEAD&&overlap(projX[i]-8,projY[i]-8,16f,16f,e.x,e.y,e.w,e.h)){e.hurt(this,20,if(projV[i]>0)1 else -1);projL[i]=0f}};particles.update(dt);val tx=(player.x+player.w/2-viewW/2+player.facing*60).coerceIn(0f,max(0f,world.cols*T-viewW));camX+=(tx-camX)*min(1f,8f*dt);camY+=((player.y+player.h/2-300).coerceIn(0f,72f)-camY)*min(1f,8f*dt)}
 private fun resize(w:Int,h:Int){sw=w;sh=h;scale=h/600f;viewW=w/scale;controls.layout(w,h);sky.shader=LinearGradient(0f,0f,0f,h.toFloat(),0xFF151C3D.toInt(),0xFF6A5A8E.toInt(),Shader.TileMode.CLAMP)}
 fun draw(c:Canvas,w:Int,h:Int,a:Float=1f){if(w!=sw||h!=sh)resize(w,h);c.drawRect(0f,0f,w.toFloat(),h.toFloat(),sky);val cx=oldX+(camX-oldX)*a;val cy=oldY+(camY-oldY)*a;c.save();c.scale(scale,scale);c.translate(-cx,-cy);val x0=floor(cx/T).toInt();for(y in 0 until world.rows)for(x in x0..x0+(viewW/T).toInt()+2)if(x in 0 until world.cols&&world.solid(x,y)){p.color=0xFF2E2A45.toInt();c.drawRect(x*T,y*T,x*T+T,y*T+T,p);if(!world.solid(x,y-1)){p.color=0xFF5D8B61.toInt();c.drawRect(x*T,y*T,x*T+T,y*T+7,p)}};for(e in enemies){p.color=if(e.flash>0)0xFFFFFFFF.toInt()else 0xFF6D5B86.toInt();c.drawOval(e.x,e.y,e.x+e.w,e.y+e.h,p);p.color=0xFFFF4F60.toInt();c.drawCircle(e.x+e.w*.7f,e.y+12,2.5f,p)};for(i in projL.indices)if(projL[i]>0){p.color=0xFF8FE8FF.toInt();c.drawCircle(projX[i],projY[i],8f,p)};if(!player.dead){p.color=0xFF2F4A7A.toInt();c.drawRect(player.x,player.y,player.x+player.w,player.y+player.h,p);p.color=0xFFE8C8A8.toInt();c.drawCircle(player.x+player.w/2,player.y+10,8f,p);if(player.atkT>0){p.color=0xFFBFF0FF.toInt();p.style=Paint.Style.STROKE;p.strokeWidth=5f;c.drawArc(player.x-24,player.y-20,player.x+player.w+24,player.y+player.h+20,if(player.facing>0)-60f else 120f,120f,false,p);p.style=Paint.Style.FILL}};particles.draw(c,p);c.restore();val u=h/600f;p.alpha=255;p.color=0x88000000.toInt();c.drawRect(20*u,20*u,300*u,58*u,p);p.color=0xFFC04848.toInt();c.drawRect(24*u,24*u,(24+252f*player.hp/maxHp())*u,38*u,p);p.color=0xFF4890D8.toInt();c.drawRect(24*u,42*u,(24+252f*player.aether/player.maxAether)*u,52*u,p);p.color=0xFFFFFFFF.toInt();p.textSize=18*u;p.textAlign=Paint.Align.LEFT;c.drawText("Lv "+level+"   Gold "+gold+"   Tonics "+inv.count("potion"),24*u,78*u,p);controls.draw(c);if(paused){p.color=0xAA000000.toInt();c.drawRect(0f,0f,w.toFloat(),h.toFloat(),p);p.color=0xFFFFFFFF.toInt();p.textAlign=Paint.Align.CENTER;p.textSize=40*u;c.drawText("PAUSED",w/2f,h/2f,p)}}
}