package com.aether.echoes
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.RectF
import kotlin.math.abs
import kotlin.math.min
import kotlin.math.sin
object Sprites{
 private val r=RectF()
 fun drawKael(c:Canvas,p:Paint,x:Float,y:Float,w:Float,h:Float,f:Int,t:Float,vx:Float,vy:Float,grounded:Boolean,attacking:Boolean,combo:Int,dashing:Boolean){val cx=x+w/2;val run=grounded&&abs(vx)>30;val ph=t*(if(abs(vx)>200)16f else 11f);val top=y+(if(run)sin(ph*2)*1.5f else sin(t*3));val speed=min(1f,abs(vx)/280f);p.strokeCap=Paint.Cap.ROUND;if(dashing){p.style=Paint.Style.FILL;p.color=0x449FE8FF;for(k in 1..2){r.set(cx-f*26*k-9,top+6,cx-f*26*k+9,y+h);c.drawOval(r,p)}};p.style=Paint.Style.STROKE;p.strokeWidth=6f;val hipY=top+h*.58f;for(leg in 0..1){val s=if(leg==0)1f else -1f;val fx=if(grounded)cx+(if(run)sin(ph)*10*s else 3*s)else cx+5*s;val fy=if(grounded)y+h-(if(run)maxOf(0f,sin(ph+s*1.6f))*4 else 0f)else if(vy<0)y+h*.88f else y+h;p.color=if(leg==0)0xFF2B3550.toInt()else 0xFF1E2438.toInt();c.drawLine(cx-1,hipY,fx,fy,p)};p.style=Paint.Style.FILL;p.color=0xFF2F4A7A.toInt();r.set(cx-9,top+h*.26f,cx+9,top+h*.6f);c.drawRoundRect(r,4f,4f,p);p.color=0xFF6B4A2E.toInt();r.set(cx-9,top+h*.5f,cx+9,top+h*.55f);c.drawRect(r,p);p.style=Paint.Style.STROKE;p.strokeWidth=5f;p.color=0xFFC0463C.toInt();var sx=cx;var sy=top+h*.27f;for(k in 1..3){val nx=cx-f*k*(6+speed*5);val ny=top+h*.27f+sin(t*9+k)*2.5f+k*1.5f;c.drawLine(sx,sy,nx,ny,p);sx=nx;sy=ny};p.style=Paint.Style.FILL;p.color=0xFF1B1626.toInt();c.drawCircle(cx-f*2,top+h*.15f,10f,p);p.color=0xFFE8C8A8.toInt();c.drawCircle(cx+f*2.5f,top+h*.17f,6.5f,p);p.color=0xFF1B1626.toInt();c.drawCircle(cx+f*5,top+h*.16f,1.4f,p);val hx=if(attacking)cx+f*18 else cx+f*(6+if(run)sin(ph)*5 else 0);val hy=if(attacking)top+h*.38f else top+h*.5f;p.style=Paint.Style.STROKE;p.strokeWidth=5f;p.color=0xFF2F4A7A.toInt();c.drawLine(cx+f*3,top+h*.3f,hx,hy,p);p.style=Paint.Style.FILL;p.color=0xFF9FE8FF.toInt();p.alpha=180;c.drawCircle((cx+hx)/2,(top+h*.3f+hy)/2,3f,p);p.alpha=255;p.style=Paint.Style.STROKE;if(attacking){val tipX=hx+f*34;val tipY=hy-8+combo*6;p.strokeWidth=4f;p.color=0xFFE8F8FF.toInt();c.drawLine(hx,hy,tipX,tipY,p);p.strokeWidth=6f+combo*2;p.color=0xFFBFF0FF.toInt();p.alpha=150;r.set(cx-46,top-2,cx+46,y+h+2);c.drawArc(r,if(f>0)-65f else 115f,130f,false,p);p.alpha=255}else{p.strokeWidth=3f;p.color=0xFF6B4A2E.toInt();c.drawLine(cx-f*6,top+h*.3f,cx-f*14,top+h*.56f,p)}}
 fun drawWolf(c:Canvas,p:Paint,x:Float,y:Float,w:Float,h:Float,d:Int,t:Float,flash:Boolean,telegraph:Boolean,moving:Boolean){val body=if(flash)0xFFFFFFFF.toInt()else if(telegraph)0xFF8A3040.toInt()else 0xFF5A4A7A.toInt();val dark=if(flash)0xFFEEEEEE.toInt()else 0xFF3A2F55.toInt();val ph=t*14;val cx=x+w/2;p.style=Paint.Style.STROKE;p.strokeWidth=5f;p.color=dark;for(i in 0..3){val fx=x+w*(.2f+.2f*i);c.drawLine(fx,y+h*.65f,fx+(if(moving)sin(ph+i*1.6)*7 else 0),y+h,p)};p.strokeWidth=6f;p.color=body;c.drawLine(cx-d*w*.45f,y+h*.42f,cx-d*w*.75f,y+h*.3f+sin(t*6)*3,p);p.style=Paint.Style.FILL;r.set(x,y+h*.25f,x+w,y+h*.8f);c.drawOval(r,p);p.style=Paint.Style.STROKE;p.strokeWidth=2f;p.color=0xFF7FE0FF.toInt();c.drawLine(cx-w*.25f,y+h*.4f,cx+w*.2f,y+h*.4f,p);val hx=cx+d*w*.5f;p.style=Paint.Style.FILL;p.color=body;c.drawCircle(hx,y+h*.38f,9f,p);c.drawCircle(hx+d*8,y+h*.45f,5f,p);p.style=Paint.Style.STROKE;p.strokeWidth=4f;p.color=dark;c.drawLine(hx-d*2,y+h*.3f,hx-d*4,y+h*.08f,p);c.drawLine(hx+d*4,y+h*.3f,hx+d*8,y+h*.1f,p);p.style=Paint.Style.FILL;p.color=0xFFFF5060.toInt();c.drawCircle(hx+d*4,y+h*.35f,2.5f,p)}
}
